### ISSUE TITLE
Recently deleted

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/2018-copy-better#32]
## Description

- **As a** user,
- **I want** to see clips that I've deleted in the past 30 days,
- **So that** I can restore clips that I may accidentally delete.

## Requirements

- Scenario 1: Delete clip
  - Given I have a clip titled "Asdf",
  - When I delete "Asdf",
  - Then "Asdf" is removed from my list of clips,
  - And "Asdf" is added to the list of recently deleted clips.
- Scenario 2: Restore clip
  - Given a clip titled "Asdf" is in the recently deleted list,
  - And "Asdf" formerly was in the folder `/Qwerty`,
  - When I restore "Asdf",
  - Then "Asdf" is added to the root folder.
- Scenario 3: Don't restore clip
  - Given a clip titled "Asdf" is in the recently deleted list,
  - And "Asdf" was added to the recently deleted list on June 1, 2022,
  - When the date reaches July 1, 2022,
  - Then "Asdf" is permanently removed from the recently deleted list.

## Tasks

- [x] Create recently deleted folder on first launch after update
- [x] Move clips and folders to deleted folder when user deletes them
- [x] Add recently deleted page
- [x] Link to deleted page from settings
- [x] Add option to permanently delete
- [x] Add option to restore
- [x] Add field on clip model to store deletion date/time
- [x] Check for overdue clips when deleted page is opened
