### ISSUE TITLE
Enable/disable color formatting in clips

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/2018-copy-better#41]
## Description

- **As a** user,
- **I want** to control whether clips store color formatting information,
- **So that** I can ignore it if I don't need it and avoid display issues.

## Tasks

- [x] Add toggle for "Store formatting information with clips" in settings, with a brief explanation that attributes such as color, font size, and bold/italics can be stored, but the keyboard always ignores it
- [x] Check setting when creating a clip
- [x] Add button in edit clip screen to remove formatting information; the button is tappable only if the clip has rich text content
- [x] Add localizations for new options
