### ISSUE TITLE
Widget configurable folder

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/2018-copy-better#43]
## Description

- **As a** user,
- **I want** to access a specific folder through the widget,
- **So that** I can efficiently copy anything I have saved.

See https://developer.apple.com/documentation/widgetkit/making-a-configurable-widget

## Tasks

- [x] Investigate widget configuration
- [x] Add new Folder widget for displaying a selected folder configurable by the user
- [x] Handle interactions with Folder widget
- [x] Handle updates to Folder widget
- [x] Add localizations for Folder widget
