### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/2018-copy-better#44]
## Description

- Move the About section in app settings to its own page to avoid dynamic cell resizing bugs
- Set defaults for new settings

## Tasks

- [x] Add new About page
- [x] Update About copy
- [x] Update localizations
- [x] Test dark mode
- [x] Set default value for "store formatting" option
- [x] Update build versions
- [x] Update readme
